"""Add binary content support for images

Revision ID: 457e2d2377ba
Revises: 2e6af49fff10
Create Date: 2025-11-22 19:34:35.657485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457e2d2377ba'
down_revision = '2e6af49fff10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_binary', sa.LargeBinary(), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    with op.batch_alter_table('project_files', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('content_binary')

    # ### end Alembic commands ###
